// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $addLover from "./routes/addLover.tsx";
import * as $api_addComment from "./routes/api/addComment.tsx";
import * as $api_checkRegister from "./routes/api/checkRegister.tsx";
import * as $api_deleteComment from "./routes/api/deleteComment.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_user from "./routes/api/user.tsx";
import * as $buscar_name_ from "./routes/buscar/[name].tsx";
import * as $deleteLover from "./routes/deleteLover.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $hobbies from "./routes/hobbies.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $AddComments from "./islands/AddComments.tsx";
import * as $AddForm from "./islands/AddForm.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DeleteComments from "./islands/DeleteComments.tsx";
import * as $DeleteForm from "./islands/DeleteForm.tsx";
import * as $FilterForm from "./islands/FilterForm.tsx";
import * as $Profile from "./islands/Profile.tsx";
import * as $RegisterForm from "./islands/RegisterForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/addLover.tsx": $addLover,
    "./routes/api/addComment.tsx": $api_addComment,
    "./routes/api/checkRegister.tsx": $api_checkRegister,
    "./routes/api/deleteComment.tsx": $api_deleteComment,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/user.tsx": $api_user,
    "./routes/buscar/[name].tsx": $buscar_name_,
    "./routes/deleteLover.tsx": $deleteLover,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/hobbies.tsx": $hobbies,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/AddComments.tsx": $AddComments,
    "./islands/AddForm.tsx": $AddForm,
    "./islands/Counter.tsx": $Counter,
    "./islands/DeleteComments.tsx": $DeleteComments,
    "./islands/DeleteForm.tsx": $DeleteForm,
    "./islands/FilterForm.tsx": $FilterForm,
    "./islands/Profile.tsx": $Profile,
    "./islands/RegisterForm.tsx": $RegisterForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
